name: Build Result image

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . -f Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/laravelcrud

      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/laravelcrud
